// ============================================
// FamTastic — Achievement definitions
// Minecraft-style: locked descriptions visible
// ============================================

export const RARITY_COLORS = {
  common:    '#9CA3AF',
  uncommon:  '#10B981',
  rare:      '#3B82F6',
  legendary: '#F59E0B',
};

export const RARITY_LABELS = {
  common:    'Vanlig',
  uncommon:  'Ovanlig',
  rare:      'Sällsynt',
  legendary: 'Legendarisk',
};

export const CATEGORIES = [
  { id: 'start',    label: '🏠 Kom igång' },
  { id: 'chores',   label: '✅ Sysslor' },
  { id: 'money',    label: '💰 Pengar' },
  { id: 'chat',     label: '💬 Chatt & Stämning' },
  { id: 'shopping', label: '🛒 Handel' },
  { id: 'location', label: '📍 Plats' },
  { id: 'special',  label: '🏆 Speciellt' },
];

// id must match what's stored in DB as achievement_id
export const ACHIEVEMENTS = [
  // ── Kom igång ──────────────────────────────────────────────────────────────
  {
    id: 'first_login',
    title: 'Välkommen hem!',
    desc: 'Logga in för första gången',
    hint: 'Välj din profilbild och PIN-kod, sedan är du inne!',
    icon: '🏠',
    category: 'start',
    rarity: 'common',
  },
  {
    id: 'explore_chat',
    title: 'Hallå familjen!',
    desc: 'Öppna familjechatten',
    hint: 'Tryck på "Chatt" i navigationen',
    icon: '👋',
    category: 'start',
    rarity: 'common',
  },
  {
    id: 'explore_schedule',
    title: 'Planeraren',
    desc: 'Öppna schemat',
    hint: 'Tryck på kalender-ikonen i topbaren',
    icon: '📅',
    category: 'start',
    rarity: 'common',
  },
  {
    id: 'explore_meals',
    title: 'Vad äter vi?',
    desc: 'Öppna Mat & Handla',
    hint: 'Tryck på "Mat" i navigationen',
    icon: '🍽️',
    category: 'start',
    rarity: 'common',
  },
  {
    id: 'explore_chores',
    title: 'Dags att jobba!',
    desc: 'Öppna Sysslor & Pengar',
    hint: 'Tryck på "Sysslor" i navigationen',
    icon: '🧹',
    category: 'start',
    rarity: 'common',
  },

  // ── Sysslor ────────────────────────────────────────────────────────────────
  {
    id: 'first_chore',
    title: 'Hjälpsam!',
    desc: 'Slutför din första syssla',
    hint: 'Hitta dina sysslor och bocka av en',
    icon: '✅',
    category: 'chores',
    rarity: 'common',
  },
  {
    id: 'all_today_chores',
    title: 'Rent bord!',
    desc: 'Klara ALLA dina sysslor på en dag',
    hint: 'Bocka av varenda syssla under en dag — inte en kvar!',
    icon: '🧹',
    category: 'chores',
    rarity: 'uncommon',
  },
  {
    id: 'chore_streak_3',
    title: 'Tre i rad',
    desc: 'Slutför sysslor 3 dagar i rad',
    hint: 'Glöm inte en enda dag — streak-räknaren är nådig',
    icon: '🔥',
    category: 'chores',
    rarity: 'common',
  },
  {
    id: 'chore_streak_7',
    title: 'En veckas hjälte',
    desc: 'Slutför sysslor 7 dagar i rad',
    hint: 'En hel vecka utan att missa en dag. Du klarar det!',
    icon: '🔥🔥',
    category: 'chores',
    rarity: 'uncommon',
  },
  {
    id: 'chore_streak_30',
    title: 'Månads-mästare',
    desc: 'Slutför sysslor 30 dagar i rad',
    hint: 'En hel månads streak. Legendariskt!',
    icon: '🌋',
    category: 'chores',
    rarity: 'legendary',
  },
  {
    id: 'chores_10',
    title: 'Flitig!',
    desc: 'Slutför 10 sysslor totalt',
    hint: 'Håll på, du når dit snabbt!',
    icon: '⭐',
    category: 'chores',
    rarity: 'common',
  },
  {
    id: 'chores_50',
    title: 'Sysslmästare',
    desc: 'Slutför 50 sysslor totalt',
    hint: '50 sysslor — det är en riktig hjälpande hand!',
    icon: '🌟',
    category: 'chores',
    rarity: 'rare',
  },
  {
    id: 'chores_100',
    title: 'Legenden',
    desc: 'Slutför 100 sysslor totalt',
    hint: 'Hundra sysslor avklarade. Du är familjens pelare!',
    icon: '👑',
    category: 'chores',
    rarity: 'legendary',
  },
  {
    id: 'pool_chore',
    title: 'Frivillig hjälte',
    desc: 'Ta en syssla från poolen',
    hint: 'Leta rätt på poolen med obesatta sysslor och snappa upp en',
    icon: '🙋',
    category: 'chores',
    rarity: 'common',
  },
  {
    id: 'pool_chore_5',
    title: 'Alltid redo',
    desc: 'Ta 5 sysslor från poolen',
    hint: 'Visa att du alltid ställer upp när familjen behöver hjälp',
    icon: '🦸',
    category: 'chores',
    rarity: 'uncommon',
  },
  {
    id: 'early_bird',
    title: 'Morgonfågel',
    desc: 'Slutför en syssla före kl 7 på morgonen',
    hint: 'Ställ klockan tidigt — familjens hjältar vaknar med solen',
    icon: '🐦‍⬛',
    category: 'chores',
    rarity: 'rare',
  },
  {
    id: 'weekend_warrior',
    title: 'Helhjälte',
    desc: 'Slutför sysslor på en helg',
    hint: 'Lördagar och söndagar är inte lediga för hjältar',
    icon: '💪',
    category: 'chores',
    rarity: 'uncommon',
  },

  // ── Pengar ─────────────────────────────────────────────────────────────────
  {
    id: 'first_goal',
    title: 'Drömmare!',
    desc: 'Skapa ditt första sparmål',
    hint: 'Gå till "Pengar" och lägg till ett mål du drömmer om',
    icon: '🎯',
    category: 'money',
    rarity: 'common',
  },
  {
    id: 'goal_completed',
    title: 'Målet nått!',
    desc: 'Nå ett sparmål',
    hint: 'Spara tills stapeln är full — du klarar det!',
    icon: '🎉',
    category: 'money',
    rarity: 'uncommon',
  },
  {
    id: 'family_goal',
    title: 'Lagspelaren',
    desc: 'Bidra till ett familjemål',
    hint: 'Familjen sparar ihop till något stort — hjälp till!',
    icon: '🤝',
    category: 'money',
    rarity: 'common',
  },
  {
    id: 'saved_500',
    title: 'Ekonomen',
    desc: 'Ha 500 kr i saldo',
    hint: 'Slutför sysslor, hoppa över godis — bygg upp bufferten',
    icon: '💰',
    category: 'money',
    rarity: 'rare',
  },

  // ── Chatt & Stämning ───────────────────────────────────────────────────────
  {
    id: 'first_message',
    title: 'Hallå där!',
    desc: 'Skicka ditt första meddelande i chatten',
    hint: 'Öppna chatten och säg något till familjen',
    icon: '💬',
    category: 'chat',
    rarity: 'common',
  },
  {
    id: 'messages_10',
    title: 'Pratkvarnen',
    desc: 'Skicka 10 meddelanden',
    hint: 'Håll konversationen igång!',
    icon: '📢',
    category: 'chat',
    rarity: 'common',
  },
  {
    id: 'messages_50',
    title: 'Pratmakaren',
    desc: 'Skicka 50 meddelanden',
    hint: '50 meddelanden — du håller familjen ihop!',
    icon: '📣',
    category: 'chat',
    rarity: 'uncommon',
  },
  {
    id: 'set_mood',
    title: 'Hur mår du?',
    desc: 'Sätt din stämning för första gången',
    hint: 'Hitta stämningskortet i chatten och välj din emoji',
    icon: '😊',
    category: 'chat',
    rarity: 'common',
  },
  {
    id: 'mood_streak_7',
    title: 'Känsloexpert',
    desc: 'Sätt stämning 7 dagar i rad',
    hint: 'Varje dag — hur mår du egentligen?',
    icon: '🌈',
    category: 'chat',
    rarity: 'uncommon',
  },
  {
    id: 'night_owl',
    title: 'Nattuglan',
    desc: 'Sätt stämning efter kl 22',
    hint: 'Fortfarande vaken sent på kvällen?',
    icon: '🦉',
    category: 'chat',
    rarity: 'rare',
  },
  {
    id: 'voted_poll',
    title: 'Din röst räknas',
    desc: 'Rösta i en familjeomröstning',
    hint: 'Vänta på att en förälder skapar en omröstning, sedan — rösta!',
    icon: '🗳️',
    category: 'chat',
    rarity: 'common',
  },
  {
    id: 'created_poll',
    title: 'Demokraten',
    desc: 'Skapa en familjeomröstning',
    hint: 'Öppna chatten och tryck på "Skapa omröstning"',
    icon: '📊',
    category: 'chat',
    rarity: 'common',
  },

  // ── Handel ─────────────────────────────────────────────────────────────────
  {
    id: 'shopping_added',
    title: 'Inhandlaren',
    desc: 'Lägg till en vara i handlingslistan',
    hint: 'Be föräldrarna aktivera "Barn bidrar" i inställningarna, sedan — handla!',
    icon: '🛒',
    category: 'shopping',
    rarity: 'common',
  },
  {
    id: 'shopping_added_5',
    title: 'Hjälpsam inköpare',
    desc: 'Lägg till 5 varor i handlingslistan',
    hint: 'Tänk på vad familjen behöver och lägg till det!',
    icon: '🛍️',
    category: 'shopping',
    rarity: 'uncommon',
  },

  // ── Plats ──────────────────────────────────────────────────────────────────
  {
    id: 'location_shared',
    title: 'Spårbar',
    desc: 'Dela din position för första gången',
    hint: 'Aktivera GPS-delning på din hemsida',
    icon: '📍',
    category: 'location',
    rarity: 'common',
  },
  {
    id: 'family_all_location',
    title: 'Hela familjen',
    desc: 'Alla familjemedlemmar delar sin position',
    hint: 'Övertyga hela familjen att aktivera GPS på samma dag',
    icon: '🗺️',
    category: 'location',
    rarity: 'rare',
  },

  // ── Speciellt ──────────────────────────────────────────────────────────────
  {
    id: 'achievements_10',
    title: 'Samlarinstinkt',
    desc: 'Lås upp 10 achievements',
    hint: 'Fortsätt använda appen — de samlas på hög!',
    icon: '🏅',
    category: 'special',
    rarity: 'uncommon',
  },
  {
    id: 'achievements_25',
    title: 'Achievements-jägaren',
    desc: 'Lås upp 25 achievements',
    hint: 'Nästan halvvägs — du vet vad du gör!',
    icon: '🥇',
    category: 'special',
    rarity: 'rare',
  },
  {
    id: 'achievements_all',
    title: 'Komplettisten',
    desc: 'Lås upp ALLA achievements',
    hint: 'Det ultimata målet — samla dem alla!',
    icon: '💎',
    category: 'special',
    rarity: 'legendary',
  },
  {
    id: 'first_week',
    title: 'Första veckan',
    desc: 'Använd appen 7 dagar i rad',
    hint: 'Kom tillbaka varje dag den första veckan',
    icon: '📆',
    category: 'special',
    rarity: 'uncommon',
  },
];

export const ACHIEVEMENT_MAP = Object.fromEntries(ACHIEVEMENTS.map(a => [a.id, a]));
export const TOTAL_ACHIEVEMENTS = ACHIEVEMENTS.length;
